apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fin
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fin
  serviceName: fin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fin
    spec:
      enableServiceLinks: false
      containers:
        - name: fin
          image: ghcr.io/seankhliao/fin
          args:
            - -data.dir=/data
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
